name: Test Homebrew Installation

on: [push, pull_request]

jobs:
  install:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macos-14, macos-15]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make scripts executable
        run: |
          chmod +x ./scripts/*.sh
          chmod +x ./tests/*.sh

      - name: Run installation script
        run: ./scripts/install.sh

      - name: Run Homebrew installation tests
        run: ./tests/installation_test.sh